/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import object.Exam;
//import object.Question;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.Timer;

/**
 *
 * @author USER
 */
public class ExamTest extends javax.swing.JFrame {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private int page = 0;

    private int tongPage;

    private int[] dsChon;

    private int[] dapAn;

    public long time;

    private String monHoc;

    private int seconds;

    private String dsCauHoi;

    private String dsDapAn;

    private Timer timmer;

    private float tongDiem;

    private float diem;

    private boolean isStop;

    public String maDe;

    /**
     * Creates new form Home
     */
    public ExamTest() {
        initComponents();

        setDeThiInfo();

        setTimeProgress();

        timmer.start();

        int len = getDsCauHoi(maDe).length;

        tongPage = len / 5;

        dsChon = new int[len];

        for (int i = 0; i < len; i++) {
            dsChon[i] = -1;
        }
        if (page == 0) {
            btnPrevious.setEnabled(false);
        }

        set(page);
    }

    private void setDeThiInfo() {

        maDe = ExamHome.maDe;
        time = ExamHome.time;
        tongDiem = ExamHome.tongDiem;
        monHoc = ExamHome.monHoc;

        lbMonHoc.setText(monHoc);
        int soCau = getDsCauHoi(maDe).length;
        lbSoCau.setText(Integer.toString(soCau));

        setTimeConvert(time);
    }

    private void setTimeConvert(long time) {
        int h = (int) (time / 3600);
        int m = (int) ((time % 3600) / 60);
        int s = (int) ((time % 3600) % 60);
        if (h > 0) {

            if (m > 0) {
                lbTime.setText(h + " : " + m + " : " + s);
            }

        } else {
            if (m > 0) {
                lbTime.setText("00 :" + m + " : " + s);

            } else {
                lbTime.setText("00 : 00: " + s);
            }
        }
    }

    private void setTimeProgress() {

        timebar.setMaximum((int) time);
        long temp = time;
        timebar.setMinimum(0);
        timmer = new Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                if (timebar.getValue() < temp) {

                    int h = (int) (time / 3600);
                    int m = (int) ((time % 3600) / 60);
                    int s = (int) ((time % 3600) % 60);
                    if (h > 0) {

                        if (m > 0) {
                            timebar.setString(h + " : " + m + " : " + s);
                        }

                    } else {
                        if (m > 0) {
                            timebar.setString(m + " : " + s);

                        } else {
                            timebar.setString("00 : " + s);
                        }
                    }
                    time--;
                    seconds++;
                    timebar.setValue(seconds);
                } else {
                    timmer.stop();

                    int show = JOptionPane.showConfirmDialog(null, "Hết thời gian làm bài", "Time up", 2);

                    if (show == 0) {
                        chamDiem();
                    }

                }

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbMonHoc = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbSoCau = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnStop = new javax.swing.JLabel();
        btnNopBai = new javax.swing.JLabel();
        btnGo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        asnw1 = new javax.swing.JRadioButton();
        asnw2 = new javax.swing.JRadioButton();
        asnw3 = new javax.swing.JRadioButton();
        asnw4 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        questionID = new javax.swing.JLabel();
        questionContent = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        answ5 = new javax.swing.JRadioButton();
        answ6 = new javax.swing.JRadioButton();
        answ7 = new javax.swing.JRadioButton();
        answ8 = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        questionID1 = new javax.swing.JLabel();
        questionContent1 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        answ9 = new javax.swing.JRadioButton();
        answ10 = new javax.swing.JRadioButton();
        answ11 = new javax.swing.JRadioButton();
        answ12 = new javax.swing.JRadioButton();
        jPanel13 = new javax.swing.JPanel();
        questionID2 = new javax.swing.JLabel();
        questionContent2 = new javax.swing.JLabel();
        panel4 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        answ13 = new javax.swing.JRadioButton();
        answ14 = new javax.swing.JRadioButton();
        answ15 = new javax.swing.JRadioButton();
        answ16 = new javax.swing.JRadioButton();
        jPanel16 = new javax.swing.JPanel();
        questionID3 = new javax.swing.JLabel();
        questionContent3 = new javax.swing.JLabel();
        panel5 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        answ17 = new javax.swing.JRadioButton();
        answ18 = new javax.swing.JRadioButton();
        answ19 = new javax.swing.JRadioButton();
        answ20 = new javax.swing.JRadioButton();
        jPanel31 = new javax.swing.JPanel();
        questionID4 = new javax.swing.JLabel();
        questionContent4 = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        timebar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        pageNumb = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        jSpinner1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSpinner1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jSpinner1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jSpinner1KeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Câu :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel3.setText("Môn học: ");

        lbMonHoc.setText("Toán");

        lbTime.setText("10 phút");

        jLabel6.setText("Thời gian:");

        jLabel7.setText("Tổng số câu: ");

        lbSoCau.setText("30");

        jLabel2.setText("Tạm dừng");

        jLabel4.setText("Nộp bài");
        
        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("image/im_stop.png"))); // NOI18N
        btnStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStopMouseClicked(evt);
            }
        });

        btnNopBai.setIcon(new javax.swing.ImageIcon(getClass().getResource("image/im_complete.png"))); // NOI18N
        btnNopBai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNopBaiMouseClicked(evt);
            }
        });

        btnGo.setIcon(new javax.swing.ImageIcon(getClass().getResource("image/im_go.png"))); // NOI18N
        btnGo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGo)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStop)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNopBai, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSoCau, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNopBai, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lbSoCau)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbMonHoc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTime)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(47, 47, 47))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        panel1.setAutoscrolls(true);

        buttonGroup1.add(asnw1);
        asnw1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                asnw1ItemStateChanged(evt);
            }
        });
        asnw1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asnw1MouseClicked(evt);
            }
        });
        asnw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asnw1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(asnw2);
        asnw2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                asnw2ItemStateChanged(evt);
            }
        });
        asnw2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asnw2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(asnw3);
        asnw3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                asnw3ItemStateChanged(evt);
            }
        });
        asnw3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asnw3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(asnw4);
        asnw4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                asnw4ItemStateChanged(evt);
            }
        });
        asnw4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asnw4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asnw1)
                    .addComponent(asnw2)
                    .addComponent(asnw3)
                    .addComponent(asnw4))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(asnw1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asnw2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asnw3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asnw4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        questionID.setText("Câu 1:");

        questionContent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(questionContent, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(questionContent, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addComponent(questionID))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        buttonGroup2.add(answ5);
        answ5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                answ5ItemStateChanged(evt);
            }
        });
        answ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answ5ActionPerformed(evt);
            }
        });

        buttonGroup2.add(answ6);
        answ6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                answ6ItemStateChanged(evt);
            }
        });
        answ6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answ6ActionPerformed(evt);
            }
        });

        buttonGroup2.add(answ7);
        answ7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                answ7ItemStateChanged(evt);
            }
        });
        answ7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answ7ActionPerformed(evt);
            }
        });

        buttonGroup2.add(answ8);
        answ8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                answ8ItemStateChanged(evt);
            }
        });
        answ8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answ8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answ5)
                    .addComponent(answ6)
                    .addComponent(answ7)
                    .addComponent(answ8))
                .addContainerGap(924, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(answ5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answ6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answ7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answ8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        questionID1.setText("Câu 1:");

        questionContent1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionID1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(questionContent1, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(questionContent1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addComponent(questionID1))
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        buttonGroup3.add(answ9);
        answ9.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                answ9ItemStateChanged(evt);
            }
        });
        answ9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answ9ActionPerformed(evt);
            }
        });

        buttonGroup3.add(answ10);
        answ10.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                answ10ItemStateChanged(evt);
            }
        });
        answ10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answ10ActionPerformed(evt);
            }
        });

        buttonGroup3.add(answ11);
        answ11.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                answ11ItemStateChanged(evt);
            }
        });
        answ11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answ11ActionPerformed(evt);
            }
        });

        buttonGroup3.add(answ12);
        answ12.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                answ12ItemStateChanged(evt);
            }
        });
        answ12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answ12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answ9)
                    .addComponent(answ10)
                    .addComponent(answ11)
                    .addComponent(answ12))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(answ9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answ10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answ11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answ12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        questionID2.setText("Câu 1:");

        questionContent2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionID2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(questionContent2, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(questionContent2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addComponent(questionID2))
        );

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        buttonGroup4.add(answ13);
        answ13.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                answ13ItemStateChanged(evt);
            }
        });
        answ13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answ13ActionPerformed(evt);
            }
        });

        buttonGroup4.add(answ14);
        answ14.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                answ14ItemStateChanged(evt);
            }
        });
        answ14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answ14ActionPerformed(evt);
            }
        });

        buttonGroup4.add(answ15);
        answ15.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                answ15ItemStateChanged(evt);
            }
        });
        answ15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answ15ActionPerformed(evt);
            }
        });

        buttonGroup4.add(answ16);
        answ16.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                answ16ItemStateChanged(evt);
            }
        });
        answ16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answ16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answ13)
                    .addComponent(answ14)
                    .addComponent(answ15)
                    .addComponent(answ16))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(answ13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answ14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answ15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answ16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        questionID3.setText("Câu 1:");

        questionContent3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionID3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(questionContent3, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(questionContent3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addComponent(questionID3))
        );

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        buttonGroup5.add(answ17);
        answ17.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                answ17ItemStateChanged(evt);
            }
        });
        answ17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answ17ActionPerformed(evt);
            }
        });

        buttonGroup5.add(answ18);
        answ18.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                answ18ItemStateChanged(evt);
            }
        });
        answ18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answ18ActionPerformed(evt);
            }
        });

        buttonGroup5.add(answ19);
        answ19.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                answ19ItemStateChanged(evt);
            }
        });
        answ19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answ19ActionPerformed(evt);
            }
        });

        buttonGroup5.add(answ20);
        answ20.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                answ20ItemStateChanged(evt);
            }
        });
        answ20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answ20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answ17)
                    .addComponent(answ18)
                    .addComponent(answ19)
                    .addComponent(answ20))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addComponent(answ17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answ18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answ19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answ20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        questionID4.setText("Câu 1:");

        questionContent4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionID4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(questionContent4, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE))
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(questionContent4, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addComponent(questionID4))
        );

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel4);

        //btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ic_previous.png"))); // NOI18N
        btnPrevious.setText("PREVIOUS");
        btnPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPreviousMouseClicked(evt);
            }
        });
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        //btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ic_next.png"))); // NOI18N
        btnNext.setText("NEXT");
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jPanel19.setBackground(new java.awt.Color(204, 204, 255));

        timebar.setBackground(new java.awt.Color(0, 204, 51));
        timebar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        timebar.setForeground(new java.awt.Color(0, 51, 204));
        timebar.setMaximum(0);
        timebar.setToolTipText("");
        timebar.setString("");
        timebar.setStringPainted(true);

        //jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ic_clock.png"))); // NOI18N

        jTextField1.setText("Thời gian");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(timebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timebar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pageNumb.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        pageNumb.setForeground(new java.awt.Color(255, 0, 51));
        pageNumb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pageNumb.setText("Page 1");

       // jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ic_again.png"))); // NOI18N
        jButton1.setText("RESET");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        //jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ic_back.png"))); // NOI18N
        jButton2.setText("RETURN");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(pageNumb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(108, 108, 108)
                .addComponent(btnPrevious)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pageNumb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asnw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asnw1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asnw1ActionPerformed

    private void asnw2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asnw2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asnw2ActionPerformed

    private void asnw3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asnw3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asnw3ActionPerformed

    private void asnw4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asnw4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asnw4ActionPerformed

    private void answ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answ5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answ5ActionPerformed

    private void answ6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answ6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answ6ActionPerformed

    private void answ7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answ7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answ7ActionPerformed

    private void answ8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answ8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answ8ActionPerformed

    private void answ9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answ9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answ9ActionPerformed

    private void answ10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answ10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answ10ActionPerformed

    private void answ11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answ11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answ11ActionPerformed

    private void answ12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answ12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answ12ActionPerformed

    private void answ13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answ13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answ13ActionPerformed

    private void answ14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answ14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answ14ActionPerformed

    private void answ15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answ15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answ15ActionPerformed

    private void answ16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answ16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answ16ActionPerformed

    private void answ17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answ17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answ17ActionPerformed

    private void answ18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answ18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answ18ActionPerformed

    private void answ19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answ19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answ19ActionPerformed

    private void answ20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answ20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answ20ActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        // TODO add your handling code here:
        if (btnNext.isEnabled()) {

            btnPrevious.setEnabled(true);

            page++;

            pageNumb.setText("Page " + page);

            set(page);

            if (page == tongPage) {
                btnNext.setEnabled(false);

            }

        }
    }//GEN-LAST:event_btnNextMouseClicked

    private void btnPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPreviousMouseClicked
        // TODO add your handling code here:
        if (btnPrevious.isEnabled()) {
            btnNext.setEnabled(true);
            page--;

            set(page);

            pageNumb.setText("Page " + page);

            if (page == 0) {
                btnPrevious.setEnabled(false);

            }
        }
    }//GEN-LAST:event_btnPreviousMouseClicked

    private void asnw1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_asnw1ItemStateChanged
        // TODO add your handling code here:

        if (asnw1.isSelected()) {
            dsChon[page * 5] = 0;
        }

    }//GEN-LAST:event_asnw1ItemStateChanged

    private void chamDiem() {
        float temp = (tongDiem / dapAn.length);
        for (int i = 0; i < dapAn.length; i++) {
            System.out.println(dsChon[i]);

            if (dsChon[i] == dapAn[i]) {
                diem += temp;

            }
        }

        DecimalFormat df = new DecimalFormat("#.##");
        String dx = df.format(diem);
        diem = Float.valueOf(dx);

        JOptionPane.showMessageDialog(null, "Bạn được :" + diem);

        diem = 0;

        comfirmDialog();
    }

    private void comfirmDialog() {
        JButton cont = new JButton("Tiếp tục");

        JButton xemlai = new JButton("Xem Đáp án");

        JButton exit = new JButton("Làm lại");

        JComponent[] inputs = new JComponent[]{
            cont, xemlai, exit
        };

        cont.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);

                ExamTest.this.setVisible(false);
                ExamTest.this.dispose();
                ExamHome hsHome = new ExamHome();
                hsHome.setLocationRelativeTo(null);
                hsHome.setVisible(true);

            }

        });

        xemlai.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);

                showDapAn(page, Color.red);
            }

        });

        exit.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);

                for (int i = 0; i < dsChon.length; i++) {
                    dsChon[i] = -1;
                }
                buttonGroup1.clearSelection();
                buttonGroup2.clearSelection();
                buttonGroup3.clearSelection();
                buttonGroup4.clearSelection();
                buttonGroup5.clearSelection();
                
                showDapAn(page, Color.black);

            }

        });

        JOptionPane.showMessageDialog(null, inputs, "Message", 1);

    }

    private void showDapAn(int page, Color c) {
        int index = page * 5;
        if (dapAn[index] == 0) {
            asnw1.setForeground(c);
        }
        if (dapAn[index] == 1) {
            asnw2.setForeground(c);
        }
        if (dapAn[index] == 2) {
            asnw3.setForeground(c);
        }
        if (dapAn[index] == 3) {
            asnw4.setForeground(c);
        }
        if (dapAn[index + 1] == 0) {
            answ5.setForeground(c);
        }
        if (dapAn[index + 1] == 1) {
            answ6.setForeground(c);
        }
        if (dapAn[index + 1] == 2) {
            answ7.setForeground(c);
        }
        if (dapAn[index + 1] == 3) {
            answ8.setForeground(c);
        }
        if (dapAn[index + 2] == 0) {
            answ9.setForeground(c);
        }
        if (dapAn[index + 2] == 1) {
            answ10.setForeground(c);
        }
        if (dapAn[index + 2] == 2) {
            answ11.setForeground(c);
        }
        if (dapAn[index + 2] == 3) {
            answ12.setForeground(c);
        }
        if (dapAn[index + 3] == 0) {
            answ13.setForeground(c);
        }
        if (dapAn[index + 3] == 1) {
            answ14.setForeground(c);
        }
        if (dapAn[index + 3] == 2) {
            answ15.setForeground(c);
        }
        if (dapAn[index + 3] == 3) {
            answ16.setForeground(c);
        }
        if (dapAn[index + 4] == 0) {
            answ17.setForeground(c);
        }
        if (dapAn[index + 4] == 1) {
            answ18.setForeground(c);
        }
        if (dapAn[index + 4] == 2) {
            answ19.setForeground(c);
        }
        if (dapAn[index + 4] == 3) {
            answ20.setForeground(c);
        }
    }
    private void asnw1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asnw1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_asnw1MouseClicked

    private void asnw2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_asnw2ItemStateChanged
        // TODO add your handling code here:
        if (asnw2.isSelected()) {
            dsChon[page * 5] = 1;
        }
    }//GEN-LAST:event_asnw2ItemStateChanged

    private void asnw3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_asnw3ItemStateChanged
        // TODO add your handling code here:
        if (asnw3.isSelected()) {
            dsChon[page * 5] = 2;
        }
    }//GEN-LAST:event_asnw3ItemStateChanged

    private void asnw4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_asnw4ItemStateChanged
        // TODO add your handling code here:
        if (asnw4.isSelected()) {
            dsChon[page * 5] = 3;
        }
    }//GEN-LAST:event_asnw4ItemStateChanged

    private void answ5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_answ5ItemStateChanged
        // TODO add your handling code here:
        if (answ5.isSelected()) {
            dsChon[page * 5 + 1] = 0;
        }
    }//GEN-LAST:event_answ5ItemStateChanged

    private void answ6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_answ6ItemStateChanged
        // TODO add your handling code here:
        if (answ6.isSelected()) {
            dsChon[page * 5 + 1] = 1;
        }
    }//GEN-LAST:event_answ6ItemStateChanged

    private void answ7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_answ7ItemStateChanged
        // TODO add your handling code here:
        if (answ7.isSelected()) {
            dsChon[page * 5 + 1] = 2;
        }

    }//GEN-LAST:event_answ7ItemStateChanged

    private void answ8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_answ8ItemStateChanged
        // TODO add your handling code here:
        if (answ8.isSelected()) {
            dsChon[page * 5 + 1] = 3;
        }
    }//GEN-LAST:event_answ8ItemStateChanged

    private void answ9ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_answ9ItemStateChanged
        // TODO add your handling code here:
        if (answ9.isSelected()) {
            dsChon[page * 5 + 2] = 0;
        }
    }//GEN-LAST:event_answ9ItemStateChanged

    private void answ10ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_answ10ItemStateChanged
        // TODO add your handling code here:
        if (answ10.isSelected()) {
            dsChon[page * 5 + 2] = 1;
        }
    }//GEN-LAST:event_answ10ItemStateChanged

    private void answ11ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_answ11ItemStateChanged
        // TODO add your handling code here:
        if (answ11.isSelected()) {
            dsChon[page * 5 + 2] = 2;
        }
    }//GEN-LAST:event_answ11ItemStateChanged

    private void answ12ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_answ12ItemStateChanged
        // TODO add your handling code here:
        if (answ12.isSelected()) {
            dsChon[page * 5 + 2] = 3;
        }
    }//GEN-LAST:event_answ12ItemStateChanged

    private void answ13ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_answ13ItemStateChanged
        // TODO add your handling code here:
        if (answ13.isSelected()) {
            dsChon[page * 5 + 3] = 0;
        }
    }//GEN-LAST:event_answ13ItemStateChanged

    private void answ14ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_answ14ItemStateChanged
        // TODO add your handling code here:
        if (answ14.isSelected()) {
            dsChon[page * 5 + 3] = 1;
        }
    }//GEN-LAST:event_answ14ItemStateChanged

    private void answ15ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_answ15ItemStateChanged
        // TODO add your handling code here:
        if (answ15.isSelected()) {
            dsChon[page * 5 + 3] = 2;
        }
    }//GEN-LAST:event_answ15ItemStateChanged

    private void answ16ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_answ16ItemStateChanged
        // TODO add your handling code here:
        if (answ16.isSelected()) {
            dsChon[page * 5 + 3] = 3;
        }
    }//GEN-LAST:event_answ16ItemStateChanged

    private void answ17ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_answ17ItemStateChanged
        // TODO add your handling code here:
        if (answ17.isSelected()) {
            dsChon[page * 5 + 4] = 0;
        }
    }//GEN-LAST:event_answ17ItemStateChanged

    private void answ18ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_answ18ItemStateChanged
        // TODO add your handling code here:
        if (answ18.isSelected()) {
            dsChon[page * 5 + 4] = 1;
        }
    }//GEN-LAST:event_answ18ItemStateChanged

    private void answ19ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_answ19ItemStateChanged
        // TODO add your handling code here:
        if (answ19.isSelected()) {
            dsChon[page * 5 + 4] = 2;
        }
    }//GEN-LAST:event_answ19ItemStateChanged

    private void answ20ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_answ20ItemStateChanged
        // TODO add your handling code here:
        if (answ20.isSelected()) {
            dsChon[page * 5 + 4] = 3;
        }
    }//GEN-LAST:event_answ20ItemStateChanged

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        dispose();
        timmer.stop();
        this.setVisible(false);
        ExamHome hsHome = new ExamHome();
        hsHome.setLocationRelativeTo(null);
        hsHome.setVisible(true);


    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

        for (int i = 0; i < dsChon.length; i++) {
            dsChon[i] = -1;
        }
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        buttonGroup4.clearSelection();
        buttonGroup5.clearSelection();  
        
        showDapAn(page, Color.black);

    }//GEN-LAST:event_jButton1MouseClicked

    private void jSpinner1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner1KeyTyped

    }//GEN-LAST:event_jSpinner1KeyTyped

    private void jSpinner1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1KeyReleased

    private void jSpinner1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1KeyPressed

    private void btnStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStopMouseClicked
        if(!isStop){
            isStop =true;
            timmer.stop();
            jLabel2.setText("Tiếp tục");
        }else{
            isStop = false;
            timmer.restart();
            jPanel4.setVisible(true);
            jLabel2.setText("Tạm dừng");
        }
    }//GEN-LAST:event_btnStopMouseClicked

    private void btnNopBaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNopBaiMouseClicked
        timmer.stop();

        chamDiem();
    }//GEN-LAST:event_btnNopBaiMouseClicked

    private void btnGoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoMouseClicked
        int numb = (int) jSpinner1.getValue();

        System.err.println("VALUE" + numb);

        page = (numb - 1) / 5;

        //System.err.println("OOOOOOÃ„â€˜Ã„â€˜Ã„â€˜Ã„â€˜Ã„â€˜" + page);

        set(page);

        pageNumb.setText("Page " + (page + 1));

        if (page == 0) {
            btnPrevious.setEnabled(false);
            btnNext.setEnabled(true);

        } else {
            if (page == tongPage) {
                btnNext.setEnabled(false);
                btnPrevious.setEnabled(true);
            } else {
                btnNext.setEnabled(true);
                btnPrevious.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnGoMouseClicked

    public void set(int page) {
        String[] ds = getDsCauHoi(maDe);
        String[] dsDA = getDsDapAn(maDe);
        int index = page * 5;

        if (page == tongPage) {
            int du = ds.length % 5;
            switch (du) {
                case 2:
                    panel3.setVisible(false);
                    panel4.setVisible(false);
                    panel5.setVisible(false);
                    setQuestionContent(ds[index].trim(), index + 1, dsDA[index].trim(), questionID, questionContent, asnw1, asnw2, asnw3, asnw4);
                    setQuestionContent(ds[index + 1].trim(), index + 2, dsDA[index].trim(), questionID1, questionContent1, answ5, answ6, answ7, answ8);

                    if (dsChon[index] == -1) {
                        buttonGroup1.clearSelection();
                    }
                    if (dsChon[index + 1] == -1) {
                        buttonGroup2.clearSelection();
                    }

                    if (dsChon[index] == 0) {
                        asnw1.setSelected(true);
                    }
                    if (dsChon[index] == 1) {
                        asnw2.setSelected(true);
                    }
                    if (dsChon[index] == 2) {
                        asnw3.setSelected(true);
                    }
                    if (dsChon[index] == 3) {
                        asnw4.setSelected(true);
                    }
                    if (dsChon[index + 1] == 0) {
                        answ5.setSelected(true);
                    }
                    if (dsChon[index + 1] == 1) {
                        answ6.setSelected(true);
                    }
                    if (dsChon[index + 1] == 2) {
                        answ7.setSelected(true);
                    }
                    if (dsChon[index + 1] == 3) {
                        answ8.setSelected(true);
                    }
                    break;
                case 3:
                    panel4.setVisible(false);
                    panel5.setVisible(false);
                    setQuestionContent(ds[index].trim(), index + 1, dsDA[index].trim(), questionID, questionContent, asnw1, asnw2, asnw3, asnw4);
                    setQuestionContent(ds[index + 1].trim(), index + 2, dsDA[index].trim(), questionID1, questionContent1, answ5, answ6, answ7, answ8);
                    setQuestionContent(ds[index + 2].trim(), index + 3, dsDA[index].trim(), questionID2, questionContent2, answ9, answ10, answ11, answ12);

                    if (dsChon[index] == -1) {
                        buttonGroup1.clearSelection();
                    }
                    if (dsChon[index + 1] == -1) {
                        buttonGroup2.clearSelection();
                    }
                    if (dsChon[index + 2] == -1) {
                        buttonGroup3.clearSelection();
                    }

                    if (dsChon[index] == 0) {
                        asnw1.setSelected(true);
                    }
                    if (dsChon[index] == 1) {
                        asnw2.setSelected(true);
                    }
                    if (dsChon[index] == 2) {
                        asnw3.setSelected(true);
                    }
                    if (dsChon[index] == 3) {
                        asnw4.setSelected(true);
                    }
                    if (dsChon[index + 1] == 0) {
                        answ5.setSelected(true);
                    }
                    if (dsChon[index + 1] == 1) {
                        answ6.setSelected(true);
                    }
                    if (dsChon[index + 1] == 2) {
                        answ7.setSelected(true);
                    }
                    if (dsChon[index + 1] == 3) {
                        answ8.setSelected(true);
                    }
                    if (dsChon[index + 2] == 0) {
                        answ9.setSelected(true);
                    }

                    if (dsChon[index + 2] == 1) {
                        answ10.setSelected(true);
                    }

                    if (dsChon[index + 2] == 2) {
                        answ11.setSelected(true);
                    }

                    if (dsChon[index + 2] == 3) {
                        answ12.setSelected(true);
                    }
                    break;
                case 4:
                    panel2.setVisible(false);
                    panel3.setVisible(false);
                    panel4.setVisible(false);
                    panel5.setVisible(false);
                    setQuestionContent(ds[index].trim(), index + 1, dsDA[index].trim(), questionID, questionContent, asnw1, asnw2, asnw3, asnw4);

                    if (dsChon[index] == -1) {
                        buttonGroup1.clearSelection();
                    }
                    if (dsChon[index] == 0) {
                        asnw1.setSelected(true);
                    }
                    if (dsChon[index] == 1) {
                        asnw2.setSelected(true);
                    }
                    if (dsChon[index] == 2) {
                        asnw3.setSelected(true);
                    }
                    if (dsChon[index] == 3) {
                        asnw4.setSelected(true);
                    }
                    break;
                case 1:
                    panel5.setVisible(false);
                    setQuestionContent(ds[index].trim(), index + 1, dsDA[index].trim(), questionID, questionContent, asnw1, asnw2, asnw3, asnw4);
                    setQuestionContent(ds[index + 1].trim(), index + 2, dsDA[index].trim(), questionID1, questionContent1, answ5, answ6, answ7, answ8);
                    setQuestionContent(ds[index + 2].trim(), index + 3, dsDA[index].trim(), questionID2, questionContent2, answ9, answ10, answ11, answ12);
                    setQuestionContent(ds[index + 3].trim(), index + 4, dsDA[index].trim(), questionID3, questionContent3, answ13, answ14, answ15, answ16);

                    if (dsChon[index] == -1) {
                        buttonGroup1.clearSelection();
                    }
                    if (dsChon[index + 1] == -1) {
                        buttonGroup2.clearSelection();
                    }
                    if (dsChon[index + 2] == -1) {
                        buttonGroup3.clearSelection();
                    }
                    if (dsChon[index + 3] == -1) {
                        buttonGroup4.clearSelection();
                    }

                    if (dsChon[index] == 0) {
                        asnw1.setSelected(true);
                    }
                    if (dsChon[index] == 1) {
                        asnw2.setSelected(true);
                    }
                    if (dsChon[index] == 2) {
                        asnw3.setSelected(true);
                    }
                    if (dsChon[index] == 3) {
                        asnw4.setSelected(true);
                    }
                    if (dsChon[index + 1] == 0) {
                        answ5.setSelected(true);
                    }
                    if (dsChon[index + 1] == 1) {
                        answ6.setSelected(true);
                    }
                    if (dsChon[index + 1] == 2) {
                        answ7.setSelected(true);
                    }
                    if (dsChon[index + 1] == 3) {
                        answ8.setSelected(true);
                    }
                    if (dsChon[index + 2] == 0) {
                        answ9.setSelected(true);
                    }

                    if (dsChon[index + 2] == 1) {
                        answ10.setSelected(true);
                    }

                    if (dsChon[index + 2] == 2) {
                        answ11.setSelected(true);
                    }

                    if (dsChon[index + 2] == 3) {
                        answ12.setSelected(true);
                    }

                    if (dsChon[index + 3] == 0) {
                        answ13.setSelected(true);
                    }

                    if (dsChon[index + 3] == 1) {
                        answ14.setSelected(true);
                    }

                    if (dsChon[index + 3] == 2) {
                        answ15.setSelected(true);
                    }

                    if (dsChon[index + 3] == 3) {
                        answ16.setSelected(true);
                    }
                    break;

            }
        } else {
            panel2.setVisible(true);
            panel3.setVisible(true);
            panel4.setVisible(true);
            panel5.setVisible(true);

            System.err.println(ds[0] + " " + ds[1]);

            setQuestionContent(ds[index].trim(), index + 1, dsDA[index].trim(), questionID, questionContent, asnw1, asnw2, asnw3, asnw4);
            setQuestionContent(ds[index + 1].trim(), index + 2, dsDA[index].trim(), questionID1, questionContent1, answ5, answ6, answ7, answ8);
            setQuestionContent(ds[index + 2].trim(), index + 3, dsDA[index].trim(), questionID2, questionContent2, answ9, answ10, answ11, answ12);
            setQuestionContent(ds[index + 3].trim(), index + 4, dsDA[index].trim(), questionID3, questionContent3, answ13, answ14, answ15, answ16);
            setQuestionContent(ds[index + 4].trim(), index + 5, dsDA[index].trim(), questionID4, questionContent4, answ17, answ18, answ19, answ20);

            if (dsChon[index] == -1) {
                buttonGroup1.clearSelection();
            }
            if (dsChon[index + 1] == -1) {
                buttonGroup2.clearSelection();
            }
            if (dsChon[index + 2] == -1) {
                buttonGroup3.clearSelection();
            }
            if (dsChon[index + 3] == -1) {
                buttonGroup4.clearSelection();
            }
            if (dsChon[index + 4] == -1) {
                buttonGroup5.clearSelection();
            }

            if (dsChon[index] == 0) {
                asnw1.setSelected(true);
            }
            if (dsChon[index] == 1) {
                asnw2.setSelected(true);
            }
            if (dsChon[index] == 2) {
                asnw3.setSelected(true);
            }
            if (dsChon[index] == 3) {
                asnw4.setSelected(true);
            }
            if (dsChon[index + 1] == 0) {
                answ5.setSelected(true);
            }
            if (dsChon[index + 1] == 1) {
                answ6.setSelected(true);
            }
            if (dsChon[index + 1] == 2) {
                answ7.setSelected(true);
            }
            if (dsChon[index + 1] == 3) {
                answ8.setSelected(true);
            }
            if (dsChon[index + 2] == 0) {
                answ9.setSelected(true);
            }

            if (dsChon[index + 2] == 1) {
                answ10.setSelected(true);
            }

            if (dsChon[index + 2] == 2) {
                answ11.setSelected(true);
            }

            if (dsChon[index + 2] == 3) {
                answ12.setSelected(true);
            }

            if (dsChon[index + 3] == 0) {
                answ13.setSelected(true);
            }

            if (dsChon[index + 3] == 1) {
                answ14.setSelected(true);
            }

            if (dsChon[index + 3] == 2) {
                answ15.setSelected(true);
            }

            if (dsChon[index + 3] == 3) {
                answ16.setSelected(true);
            }

            if (dsChon[index + 4] == 0) {
                answ17.setSelected(true);
            }
            if (dsChon[index + 4] == 1) {
                answ18.setSelected(true);
            }
            if (dsChon[index + 4] == 2) {
                answ19.setSelected(true);
            }
            if (dsChon[index + 4] == 3) {
                answ20.setSelected(true);
            }
        }
    }

    public String[] getDsCauHoi(String maDe) {

        Exam rs = ExamQuery.getDeThi(maDe);
        dsCauHoi = rs.getListQuestionID();

        String[] ds = dsCauHoi.split(";");

        return ds;
    }

    

    public String[] getDsDapAn(String maDe) {
        Exam rs = ExamQuery.getDeThi(maDe);

        dsDapAn = rs.getListRandom();

        String[] ds = dsDapAn.split(";");

        dapAn = new int[ds.length];

        for (int i = 0; i < ds.length; i++) {

            dapAn[i] = ds[i].indexOf("1");

            System.out.println(dapAn[i]);
        }

        return ds;

    }

    public static String getIndexDapAn(int index, String maCauHoi) {
        if (index == 1) {
            String da = ExamQuery.getQuestion(maCauHoi).getAnsA();
            return da;
        }
        if (index == 2) {
            String da = ExamQuery.getQuestion(maCauHoi).getAnsB();
            return da;
        }
        if (index == 3) {
            String da = ExamQuery.getQuestion(maCauHoi).getAnsC();
            return da;
        }
        if (index == 4) {
            String da = ExamQuery.getQuestion(maCauHoi).getAnsD();
            return da;
        }
        return null;
    }

    public void setQuestionContent(String maCauHoi, int index, String dsDapAn, JLabel questionID,
            JLabel questionContent, JRadioButton answ1,
            JRadioButton answ2, JRadioButton answ3, JRadioButton answ4) {

        String content = ExamQuery.getQuestion(maCauHoi).getQuestionContent();

        System.err.println(content + "   kh");

        questionID.setText("Câu : " + Integer.toString(index));
        questionContent.setText(content);

        String a = dsDapAn.substring(0, 1);
        String b = dsDapAn.substring(1, 2);
        String c = dsDapAn.substring(2, 3);
        String d = dsDapAn.substring(3);

        answ1.setText("A :  " + getIndexDapAn(Integer.parseInt(a), maCauHoi));
        answ2.setText("B :  " + getIndexDapAn(Integer.parseInt(b), maCauHoi));
        answ3.setText("C :  " + getIndexDapAn(Integer.parseInt(c), maCauHoi));
        answ4.setText("D :  " + getIndexDapAn(Integer.parseInt(d), maCauHoi));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExamTest gv = new ExamTest();
                gv.setLocationRelativeTo(null);

                gv.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton answ10;
    private javax.swing.JRadioButton answ11;
    private javax.swing.JRadioButton answ12;
    private javax.swing.JRadioButton answ13;
    private javax.swing.JRadioButton answ14;
    private javax.swing.JRadioButton answ15;
    private javax.swing.JRadioButton answ16;
    private javax.swing.JRadioButton answ17;
    private javax.swing.JRadioButton answ18;
    private javax.swing.JRadioButton answ19;
    private javax.swing.JRadioButton answ20;
    private javax.swing.JRadioButton answ5;
    private javax.swing.JRadioButton answ6;
    private javax.swing.JRadioButton answ7;
    private javax.swing.JRadioButton answ8;
    private javax.swing.JRadioButton answ9;
    private javax.swing.JRadioButton asnw1;
    private javax.swing.JRadioButton asnw2;
    private javax.swing.JRadioButton asnw3;
    private javax.swing.JRadioButton asnw4;
    private javax.swing.JLabel btnGo;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel btnNopBai;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JLabel btnStop;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbMonHoc;
    private javax.swing.JLabel lbSoCau;
    private javax.swing.JLabel lbTime;
    private javax.swing.JLabel pageNumb;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JLabel questionContent;
    private javax.swing.JLabel questionContent1;
    private javax.swing.JLabel questionContent2;
    private javax.swing.JLabel questionContent3;
    private javax.swing.JLabel questionContent4;
    private javax.swing.JLabel questionID;
    private javax.swing.JLabel questionID1;
    private javax.swing.JLabel questionID2;
    private javax.swing.JLabel questionID3;
    private javax.swing.JLabel questionID4;
    private javax.swing.JProgressBar timebar;
    // End of variables declaration//GEN-END:variables
}
